# Clippy Configuration for The Hack: Ghost Protocol
# This file configures clippy lints for the project
# Run with: cargo clippy --all-targets --all-features -- -D warnings

# NOTE: Clippy lints are controlled via command-line flags in CI/CD
# This file only controls clippy.toml-specific settings

# Complexity thresholds
cognitive-complexity-threshold = 30
type-complexity-threshold = 500

# Allow certain patterns
too-many-arguments-threshold = 10
too-many-lines-threshold = 200

# Documentation requirements
missing-docs-in-crate-items = false
