# Clippy Configuration for The Hack: Ghost Protocol
# Configure via .cargo/config.toml or command line

# This file documents the clippy lints we enable/disable
# Run with: cargo clippy -- -D warnings

# Deny all warnings in CI
warn = ["clippy::all", "clippy::pedantic", "clippy::nursery"]

# Allow certain pedantic lints
allow = [
  "clippy::module_name_repetitions",
  "clippy::must_use_candidate",
  "clippy::missing_errors_doc",
  "clippy::missing_panics_doc",
]
