# cargo-deny configuration for The Hack: Ghost Protocol
# https://embarkstudios.github.io/cargo-deny/

# Note: Run with `cargo install cargo-deny` then `cargo deny check`

[advisories]
# Security vulnerability database check
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "warn"
ignore = []

[licenses]
# License compliance
unlicensed = "deny"
allow = [
  "MIT",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "Unicode-DFS-2016",
]
deny = ["GPL-2.0", "GPL-3.0", "AGPL-3.0"]
copyleft = "warn"
allow-osi-fsf-free = "both"
default = "deny"
confidence-threshold = 0.8

[bans]
# Disallow certain crates
multiple-versions = "warn"
wildcards = "warn"
highlight = "all"
skip = []
skip-tree = []

[sources]
# Only allow crates from crates.io
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[sources.allow-org]
# Allow GitHub organizations
github = []
