# Rustfmt Configuration for The Hack: Ghost Protocol
# Only stable features (no nightly required)
# https://rust-lang.github.io/rustfmt/

edition = "2021"
max_width = 100
use_small_heuristics = "Default"
tab_spaces = 4
reorder_imports = true
match_arm_leading_pipes = "Never"
use_field_init_shorthand = true
use_try_shorthand = true
merge_derives = true
reorder_modules = true
newline_style = "Auto"
remove_nested_parens = true
