# Cargo Configuration for The Hack: Ghost Protocol
# https://doc.rust-lang.org/cargo/reference/config.html

[build]
# Number of parallel jobs, defaults to # of CPUs
# jobs = 1

[term]
# Enable color output
color = 'auto'

[alias]
# Convenient cargo aliases
b = "build"
br = "build --release"
t = "test"
r = "run"
rr = "run --release"
c = "check"
cl = "clippy -- -D warnings"
f = "fmt"
doc = "doc --no-deps --open"

# Complete check
full-check = "clippy --all-targets --all-features -- -D warnings"

# Watch mode (requires cargo-watch)
# Install: cargo install cargo-watch
watch = "watch -x 'run'"
watch-test = "watch -x 'test'"

[target.x86_64-pc-windows-msvc]
# Windows-specific configuration

[target.x86_64-unknown-linux-gnu]
# Linux-specific configuration

[target.x86_64-apple-darwin]
# macOS-specific configuration
